In [64]:
import os
import numpy as np
import pandas as pd

In [65]:
moviesdf = pd.read_csv(r"C:\Users\somep\Documents\Flatiron\DS-Live-022023\DS-Live-022023\ml-latest-small\movies.csv")

In [66]:
moviesdf

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [67]:
ratingsdf = pd.read_csv(r"C:\Users\somep\Documents\Flatiron\DS-Live-022023\DS-Live-022023\ml-latest-small\ratings.csv")

In [68]:
ratingsdf

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [69]:
tagsdf = pd.read_csv(r"C:\Users\somep\Documents\Flatiron\DS-Live-022023\DS-Live-022023\ml-latest-small\tags.csv")

In [70]:
tagsdf

      userId  movieId               tag   timestamp
0          2    60756             funny  1445714994
1          2    60756   Highly quotable  1445714996
2          2    60756      will ferrell  1445714992
3          2    89774      Boxing story  1445715207
4          2    89774               MMA  1445715200
...      ...      ...               ...         ...
3678     606     7382         for katie  1171234019
3679     606     7936           austere  1173392334
3680     610     3265            gun fu  1493843984
3681     610     3265  heroic bloodshed  1493843978
3682     610   168248  Heroic Bloodshed  1493844270

[3683 rows x 4 columns]

In [71]:
display(moviesdf.head())
display(ratingsdf.head())
display(tagsdf.head())

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [72]:
final_movies = pd.merge(ratingsdf, moviesdf, on="movieId", how="left")
final_movies = pd.merge(final_movies, tagsdf, on="movieId", how="left")

In [73]:
final_movies

,userId_x,movieId,rating,timestamp_x,title,genres,userId_y,tag,timestamp_y
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,336.0,pixar,1.139046e+09
1,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,474.0,pixar,1.137207e+09
2,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,567.0,fun,1.525286e+09
3,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance,289.0,moldy,1.143425e+09
4,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance,289.0,old,1.143425e+09
...,...,...,...,...,...,...,...,...,...
285757,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi,567.0,emotional,1.525284e+09
285758,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi,567.0,gritty,1.525284e+09
285759,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi,567.0,heartbreaking,1.525284e+09
285760,610,168252,5.0,1493846352,Logan (2017),Action|Sci-Fi,567.0,predictible plot,1.525284e+09
285761,610,170875,3.0,1493846415,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,NaN,NaN,NaN

In [74]:
final_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 285762 entries, 0 to 285761
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   userId_x     285762 non-null  int64
 1   movieId      285762 non-null  int64
 2   rating       285762 non-null  float64
 3   timestamp_x  285762 non-null  int64
 4   title        285762 non-null  object
 5   genres       285762 non-null  object
 6   userId_y     233213 non-null  float64
 7   tag          233213 non-null  object
 8   timestamp_y  233213 non-null  float64
dtypes: float64(3), int64(3), object(3)
memory usage: 21.8+ MB

In [75]:
final_movies = final_movies.drop(columns=["timestamp_x", "timestamp_y", "userId_x"])

In [76]:
final_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 285762 entries, 0 to 285761
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   movieId   285762 non-null  int64
 1   rating    285762 non-null  float64
 2   title     285762 non-null  object
 3   genres    285762 non-null  object
 4   userId_y  233213 non-null  float64
 5   tag       233213 non-null  object
dtypes: float64(2), int64(1), object(3)
memory usage: 15.3+ MB

In [77]:
final_movies.isna().sum()

movieId         0
rating          0
title           0
genres          0
userId_y    52549
tag         52549
dtype: int64

In [78]:
final_movies.isnull().sum()

movieId         0
rating          0
title           0
genres          0
userId_y    52549
tag         52549
dtype: int64

In [79]:
final_movies = final_movies.dropna()

In [80]:
final_movies

,movieId,rating,title,genres,userId_y,tag
0,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,336.0,pixar
1,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,474.0,pixar
2,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,567.0,fun
3,3,4.0,Grumpier Old Men (1995),Comedy|Romance,289.0,moldy
4,3,4.0,Grumpier Old Men (1995),Comedy|Romance,289.0,old
...,...,...,...,...,...,...
285756,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,dark
285757,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,emotional
285758,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,gritty
285759,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,heartbreaking
285760,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,predictible plot

In [81]:
final_movies.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
285756     True
285757     True
285758     True
285759     True
285760     True
Length: 233213, dtype: bool

In [19]:
final_movies['overview']= final_movies['title'] + final_movies['genres'] + final_movies['tag']

In [20]:
final_movies

,movieId,rating,title,genres,userId_y,tag,overview
0,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,336.0,pixar,Toy Story (1995)Adventure|Animation|Children|C...
1,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,474.0,pixar,Toy Story (1995)Adventure|Animation|Children|C...
2,1,4.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,567.0,fun,Toy Story (1995)Adventure|Animation|Children|C...
3,3,4.0,Grumpier Old Men (1995),Comedy|Romance,289.0,moldy,Grumpier Old Men (1995)Comedy|Romancemoldy
4,3,4.0,Grumpier Old Men (1995),Comedy|Romance,289.0,old,Grumpier Old Men (1995)Comedy|Romanceold
...,...,...,...,...,...,...,...
285756,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,dark,Logan (2017)Action|Sci-Fidark
285757,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,emotional,Logan (2017)Action|Sci-Fiemotional
285758,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,gritty,Logan (2017)Action|Sci-Figritty
285759,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,heartbreaking,Logan (2017)Action|Sci-Fiheartbreaking
285760,168252,5.0,Logan (2017),Action|Sci-Fi,567.0,predictible plot,Logan (2017)Action|Sci-Fipredictible plot

In [40]:
final_movies['genres'].unique()

array(['Adventure|Animation|Children|Comedy|Fantasy', 'Comedy|Romance',
       'Mystery|Thriller', 'Crime|Mystery|Thriller',
       'Adventure|Comedy|Crime|Romance', 'Action|Drama|War', 'Comedy',
       'Comedy|Drama', 'Action|Adventure|Sci-Fi',
       'Comedy|Crime|Drama|Thriller', 'Action|Crime|Drama|Thriller',
       'Comedy|Drama|Romance|War', 'Thriller',
       'Action|Adventure|Sci-Fi|Thriller', 'Drama|War',
       'Comedy|Romance|Thriller', 'Action|Adventure|Comedy|Romance',
       'Adventure|Drama|Western', 'Action|Crime|Thriller',
       'Crime|Horror|Thriller', 'Animation|Children|Fantasy|Musical',
       'Action|Adventure|Mystery|Thriller',
       'Adventure|Animation|Children|Comedy|Fantasy|Sci-Fi',
       'Action|Adventure|Thriller', 'Action|Adventure|Romance|Thriller',
       'Adventure|Children|Fantasy|Musical', 'Drama|Mystery',
       'Action|Adventure|Romance', 'Drama|Fantasy|Romance', 'Drama',
       'Animation|Children|Drama|Musical',
       'Adventure|Animation|Children|Musical',
       'Adventure|Animation|Children|Fantasy|Musical',
       'Children|Drama|Sci-Fi', 'Adventure|Comedy|Fantasy',
       'Action|Adventure|Comedy|Fantasy|Romance', 'Action|Adventure',
       'Crime|Drama|Sci-Fi|Thriller', 'Crime|Drama', 'Horror|Sci-Fi',
       'Crime|Horror', 'Action|Comedy|Musical',
       'Action|Drama|Romance|War', 'Action|Sci-Fi|Thriller', 'Horror',
       'Adventure|Comedy|Sci-Fi', 'Comedy|Fantasy', 'Action|Crime',
       'Action|Comedy|Crime|Drama|Sci-Fi', 'Action|Romance|War|Western',
       'Comedy|Crime|Romance', 'Action|Comedy|Sci-Fi',
       'Crime|Film-Noir|Mystery|Thriller', 'Drama|Mystery|Thriller',
       'Comedy|Crime', 'Adventure|Children|Comedy|Fantasy|Sci-Fi',
       'Action|Crime|Drama|Mystery|Thriller',
       'Animation|Children|Comedy|Musical', 'Action|Adventure|Fantasy',
       'Adventure|Animation|Children|Fantasy',
       'Adventure|Animation|Children|Drama', 'Crime|Drama|Thriller',
       'Adventure|Comedy', 'Action|Drama|Sci-Fi', 'Action|Sci-Fi',
       'Drama|Horror|Sci-Fi', 'Animation|Comedy|Musical',
       'Adventure|Animation|Children|Drama|Sci-Fi',
       'Comedy|Drama|Fantasy|Romance', 'Adventure|Fantasy',
       'Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery',
       'Comedy|Horror|Mystery|Thriller', 'Action|Adventure|Drama',
       'Comedy|Western', 'Drama|Romance', 'Action|Crime|Drama|IMAX',
       'Action|Comedy|Horror',
       'Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX', 'Documentary',
       'Action|Adventure|Crime|IMAX', 'Action|Drama|Western',
       'Comedy|Crime|Drama', 'Sci-Fi|IMAX', 'Action|Crime|Drama|War',
       'Adventure|Animation|Comedy', 'Comedy|Drama|Musical|Romance',
       'Children|Drama|Fantasy', 'Animation|Children|Comedy|Romance',
       'Comedy|Drama|Romance', 'Comedy|Crime|Thriller',
       'Mystery|Sci-Fi|Thriller', 'Comedy|Drama|Thriller',
       'Adventure|Animation|Children|Comedy|Musical',
       'Animation|Children|Fantasy|Musical|Romance|IMAX',
       'Drama|Mystery|Western', 'Comedy|Musical|Romance',
       'Action|Adventure|Mystery|Romance|Thriller', 'Drama|Romance|War',
       'Film-Noir|Romance|Thriller', 'Crime|Drama|Film-Noir',
       'Adventure|Drama|War', 'Adventure|Drama', 'Drama|Western',
       'Action|Western', 'Crime|Drama|Mystery|Thriller',
       'Drama|Musical|Romance', 'Crime|Drama|Film-Noir|Thriller',
       'Drama|Horror|Mystery', 'Mystery|Romance|Thriller',
       'Comedy|Drama|Musical', 'Action|Drama|Romance',
       'Adventure|Comedy|Crime', 'Action|Drama',
       'Adventure|Children|Fantasy', 'Drama|Fantasy|Horror|Thriller|War',
       'Children|Drama', 'Adventure|Drama|IMAX',
       'Action|Adventure|Comedy|Crime',
       'Adventure|Animation|Children|Drama|Musical|IMAX',
       'Action|Adventure|Comedy|Romance|Thriller',
       'Children|Comedy|Fantasy', 'Action|Thriller',
       'Animation|Children|Drama|Fantasy|Musical',
       'Crime|Drama|Horror|Mystery|Thriller', 'Drama|Horror|Thriller',
       'Action|Adventure|Mystery|Sci-Fi', 'Drama|Thriller|War',
       'Drama|Thriller', 'Comedy|Drama|Fantasy', 'Adventure|Drama|Sci-Fi',
       'Action|Romance|Thriller', 'Drama|Musical',
       'Comedy|Drama|Fantasy|Romance|Thriller', 'Animation|Children',
       'Adventure|Children', 'Comedy|War', 'Action|Romance',
       'Comedy|Drama|Sci-Fi', 'Action|Romance|Sci-Fi|Thriller',
       'Comedy|Fantasy|Sci-Fi', 'Drama|Sci-Fi',
       'Adventure|Animation|Children|Comedy|Fantasy|Romance',
       'Drama|Fantasy|Mystery|Sci-Fi', 'Crime|Thriller',
       'Action|Crime|Mystery|Sci-Fi|Thriller', 'Horror|Sci-Fi|Thriller',
       'Adventure|Animation|Fantasy', 'Comedy|Crime|Drama|Musical',
       'Action|Adventure|Comedy|Fantasy', 'Comedy|Musical',
       'Action|Adventure|Drama|Fantasy',
       'Adventure|Animation|Children|Comedy|Musical|Romance',
       'Adventure|Fantasy|IMAX', 'Action|Adventure|Sci-Fi|IMAX',
       'Horror|Mystery|Thriller',
       'Action|Adventure|Animation|Children|Comedy',
       'Action|Crime|Film-Noir|Mystery|Thriller', 'Drama|Fantasy|Mystery',
       'Children|Comedy', 'Drama|Film-Noir|Romance',
       'Drama|Romance|Thriller', 'Children|Comedy|Fantasy|Musical',
       'Adventure|Animation|Children|Comedy',
       'Drama|Fantasy|Romance|Thriller', 'Action|Adventure|Thriller|IMAX',
       'Comedy|Fantasy|Romance', 'Action|Adventure|Horror|Sci-Fi',
       'Drama|Sci-Fi|Thriller', 'Adventure|Animation|Children',
       'Animation|Children|Drama|Fantasy', 'Action|Horror|Sci-Fi',
       'Action|Drama|Thriller', 'Drama|Mystery|Sci-Fi|Thriller',
       'Animation|Children|Drama', 'Action|Horror|Sci-Fi|Thriller|IMAX',
       'Adventure|Animation|Children|Romance|Sci-Fi',
       'Action|Adventure|Drama|Sci-Fi|Thriller', 'Action|Sci-Fi|IMAX',
       'Adventure|Drama|Thriller|IMAX', 'Animation|Comedy',
       'Animation|Children|Comedy', 'Film-Noir|Mystery',
       'Animation|Children|Comedy|Crime', 'Action|Adventure|Western',
       'Adventure|Animation|Children|Comedy|Sci-Fi',
       'Crime|Film-Noir|Thriller', 'Crime|Thriller|War',
       'Comedy|Drama|War', 'Action|Comedy|Fantasy',
       'Action|Adventure|Animation|Drama|Fantasy',
       'Action|Adventure|Animation|Children|Fantasy|Sci-Fi',
       'Drama|Romance|Sci-Fi', 'Drama|Fantasy|Thriller',
       'Action|Crime|Drama', 'Action|Adventure|Crime|Drama|Thriller',
       'Crime|Drama|Mystery', 'Adventure|Animation|Fantasy|Romance',
       'Western', 'Film-Noir|Mystery|Thriller',
       'Action|Adventure|Children|Drama',
       'Fantasy|Horror|Mystery|Romance', 'Comedy|Mystery|Thriller',
       'Adventure|Children|Comedy|Fantasy|IMAX',
       'Action|Crime|Drama|Thriller|War',
       'Animation|Comedy|Fantasy|Musical|Romance',
       'Comedy|Crime|Mystery|Thriller',
       'Action|Adventure|Comedy|Crime|Fantasy',
       'Comedy|Drama|Musical|Sci-Fi', 'Animation|Comedy|Drama',
       'Action|Comedy|Fantasy|Musical|Romance', 'Comedy|Drama|Mystery',
       'Sci-Fi', 'Adventure|Children|Comedy|Musical',
       'Comedy|Mystery|Romance', 'Comedy|Sci-Fi',
       'Drama|Mystery|Romance|Thriller',
       'Comedy|Crime|Mystery|Romance|Thriller', 'Horror|Thriller',
       'Drama|Fantasy|Horror|Thriller', 'Adventure|Children|Comedy',
       'Action|Mystery|Sci-Fi', 'Adventure|Film-Noir|Sci-Fi|Thriller',
       'Sci-Fi|Thriller', 'Children|Drama|Fantasy|Mystery|Thriller',
       'Action|Horror|Thriller', 'Action|Drama|Romance|Sci-Fi',
       'Animation|Musical', 'Comedy|Horror',
       'Adventure|Comedy|Fantasy|Sci-Fi', 'Children|Comedy|Romance',
       'Animation|Children|Fantasy|Musical|Romance', 'Musical|Romance',
       'Action|Comedy|Romance', 'Musical|Romance|War',
       'Action|Adventure|Children|Comedy',
       'Adventure|Animation|Fantasy|Sci-Fi', 'Action|Adventure|Comedy',
       'Adventure|Children|Drama', 'Adventure|Children|Comedy|Mystery',
       'Adventure|Fantasy|Thriller|IMAX', 'Action|Comedy|Fantasy|IMAX',
       'Adventure|Romance|Sci-Fi|IMAX',
       'Action|Adventure|Animation|Children|Comedy|Fantasy',
       'Action|Animation|Comedy', 'Action|Comedy', 'Adventure|Sci-Fi',
       'Action|Crime|Sci-Fi', 'Comedy|Documentary|Drama',
       'Animation|Fantasy|Thriller',
       'Adventure|Drama|Fantasy|Mystery|Sci-Fi',
       'Action|Crime|Romance|Thriller',
       'Action|Adventure|Animation|Sci-Fi', 'Crime|Film-Noir|Mystery',
       'Crime|Film-Noir', 'Animation|Comedy|Fantasy',
       'Drama|Film-Noir|Thriller', 'Mystery',
       'Action|Adventure|Drama|Thriller', 'Drama|Fantasy|Mystery|Romance',
       'Action|Comedy|Crime', 'Adventure|Comedy|Romance|War',
       'Action|Adventure|Drama|War', 'Action|Horror',
       'Crime|Drama|Mystery|Romance|Thriller',
       'Action|Adventure|Drama|Fantasy|Thriller',
       'Action|Adventure|Crime|Drama|Thriller|War',
       'Action|Comedy|Crime|Mystery', 'Action|Crime|Drama|Western',
       'Children|Drama|Fantasy|Romance', 'Documentary|War',
       'Action|Adventure|Fantasy|Sci-Fi', 'Action|Adventure|Drama|Sci-Fi',
       'Adventure|Drama|Thriller', 'Adventure|Drama|Romance',
       'Action|Animation|Drama|Fantasy|Sci-Fi',
       'Animation|Mystery|Sci-Fi', 'Animation|Comedy|Fantasy|Sci-Fi',
       'Action|Comedy|Fantasy|Sci-Fi', 'Action|Drama|Thriller|War',
       'Horror|Mystery', 'Crime|Horror|Mystery|Thriller',
       'Action|Adventure|Drama|Western',
       'Comedy|Crime|Drama|Romance|Thriller', 'Documentary|IMAX',
       'Action|Fantasy|Sci-Fi', 'Action|Animation|Drama|Sci-Fi',
       'Adventure|Children|Comedy|Fantasy',
       'Action|Adventure|Fantasy|Sci-Fi|IMAX',
       'Action|Mystery|Sci-Fi|Thriller',
       'Drama|Horror|Mystery|Sci-Fi|Thriller',
       'Action|Adventure|Children', 'Action|Comedy|Crime|Horror',
       'Action|Adventure|Children|Sci-Fi', 'Fantasy|Horror|Thriller',
       'Action|Drama|Horror|Thriller', 'Animation|Drama|War',
       'Crime|Mystery', 'Children|Comedy|Drama', 'Adventure|Documentary',
       'Action|Adventure|Animation|Children|Comedy|Sci-Fi',
       'Adventure|Crime|Drama', 'Drama|Romance|Western', 'Musical',
       'Adventure|Comedy|Musical|Sci-Fi', 'Crime|Drama|Romance',
       'Adventure|Animation|Children|Drama|Fantasy',
       'Action|Animation|Sci-Fi|Thriller', 'Crime|Drama|Horror',
       'Comedy|Musical|Romance|Western',
       'Animation|Comedy|Drama|Fantasy|Sci-Fi',
       'Adventure|Comedy|Romance', 'Romance', 'Romance|Thriller',
       'Adventure|Animation|Comedy|Fantasy|Romance',
       'Drama|Film-Noir|Mystery|Romance', 'Comedy|Documentary',
       'Adventure|Comedy|Musical', 'Musical|Romance|Western', 'Fantasy',
       'Drama|Fantasy', 'Action|Animation|Comedy|Sci-Fi',
       'Adventure|Animation|Drama', 'Drama|Film-Noir',
       'Adventure|Drama|Fantasy', 'Documentary|Drama',
       'Children|Comedy|Crime|Drama|Fantasy',
       'Crime|Drama|Fantasy|Mystery|Thriller', 'Documentary|Musical',
       'Animation|Drama|Romance', 'Drama|Horror',
       'Action|Mystery|Thriller', 'Action|Crime|Horror',
       'Comedy|Horror|Thriller', 'Film-Noir', 'Animation',
       'Adventure|Children|Comedy|Romance|Sci-Fi',
       'Action|Crime|Drama|Horror|Thriller',
       'Action|Animation|Comedy|Horror|Thriller', 'Drama|Fantasy|Horror',
       'Adventure|Comedy|Fantasy|Musical',
       'Action|Adventure|Animation|Crime|Fantasy',
       'Comedy|Crime|Mystery|Romance', 'Action|Horror|Sci-Fi|Thriller',
       'Adventure', 'Comedy|Romance|Sci-Fi',
       'Drama|Film-Noir|Mystery|Thriller',
       'Adventure|Comedy|Crime|Drama|Romance', 'Romance|War',
       'Adventure|Crime|Drama|Thriller', 'Animation|Children|Musical',
       'Drama|War|Western', 'Drama|Fantasy|Musical|Romance',
       'Comedy|Crime|Mystery', 'Crime|Drama|Film-Noir|Romance|Thriller',
       'Drama|Horror|Romance|Thriller',
       'Comedy|Crime|Drama|Mystery|Romance',
       'Comedy|Crime|Drama|Musical|Mystery|Romance',
       'Drama|Horror|Mystery|Thriller', 'Drama|Thriller|Western',
       'Drama|Film-Noir|Mystery', 'Animation|Drama|Sci-Fi|IMAX',
       'Animation|Drama|Romance|Sci-Fi',
       'Action|Animation|Mystery|Sci-Fi', 'Animation|Fantasy',
       'Romance|Sci-Fi', 'Adventure|Animation|Drama|Horror',
       'Romance|Sci-Fi|Thriller', 'Animation|Drama|Fantasy',
       'Adventure|Animation', '(no genres listed)'], dtype=object)

In [43]:
pd.value_counts(final_movies['genres']).head(30)

Comedy|Crime|Drama|Thriller                        56851
Action|Crime|Drama|Thriller                        16725
Action|Adventure|Sci-Fi                            11939
Drama                                               6242
Comedy                                              5486
Action|Sci-Fi|Thriller                              5044
Adventure|Drama|Sci-Fi                              4905
Crime|Drama                                         4672
Comedy|Romance                                      4528
Drama|Romance|Sci-Fi                                4454
Comedy|Crime                                        4346
Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX     3718
Comedy|Drama|Romance|War                            3665
Drama|Mystery|Sci-Fi|Thriller                       3527
Mystery|Thriller                                    3510
Action|Drama|War                                    3183
Comedy|Drama|Romance                                3123
Action|Adventure|Sci-Fi|IMAX                        3087
Drama|Mystery|Thriller                              2888
Crime|Mystery|Thriller                              2844
Drama|Romance                                       2550
Drama|War                                           2505
Adventure|Fantasy                                   2034
Action|Sci-Fi                                       1966
Crime|Drama|Thriller                                1941
Action|Adventure                                    1893
Action|Adventure|Drama|Fantasy                      1850
Mystery|Sci-Fi|Thriller                             1835
Crime|Horror|Thriller                               1674
Action|Crime|Thriller                               1641
Name: genres, dtype: int64

In [45]:
len(final_movies['genres'].unique())

370

In [44]:
pd.value_counts(final_movies['tag']).head(30)

sci-fi               2527
thought-provoking    2487
twist ending         2434
atmospheric          2227
dark comedy          2056
superhero            1787
psychology           1750
Disney               1748
time travel          1730
suspense             1716
classic              1625
imdb top 250         1506
quirky               1414
space                1413
mindfuck             1401
disturbing           1378
psychological        1339
surreal              1336
action               1322
great soundtrack     1299
stylized             1222
crime                1190
aliens               1155
dreamlike            1144
funny                1092
violence             1092
cult film            1078
Mafia                1060
Quentin Tarantino    1053
music                1030
Name: tag, dtype: int64

In [46]:
len(final_movies['tag'].unique())

1584

In [47]:
pd.get_dummies(final_movies, columns=['genres', 'tag'])

,movieId,rating,title,userId_y,overview,genres_(no genres listed),genres_Action|Adventure,genres_Action|Adventure|Animation|Children|Comedy,genres_Action|Adventure|Animation|Children|Comedy|Fantasy,genres_Action|Adventure|Animation|Children|Comedy|Sci-Fi,...,tag_women,tag_wonderwoman,tag_workplace,tag_writing,tag_wrongful imprisonment,tag_wry,tag_younger men,tag_zither,tag_zoe kazan,tag_zombies
0,1,4.0,Toy Story (1995),336.0,Toy Story (1995)Adventure|Animation|Children|C...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,4.0,Toy Story (1995),474.0,Toy Story (1995)Adventure|Animation|Children|C...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,4.0,Toy Story (1995),567.0,Toy Story (1995)Adventure|Animation|Children|C...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,4.0,Grumpier Old Men (1995),289.0,Grumpier Old Men (1995)Comedy|Romancemoldy,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,4.0,Grumpier Old Men (1995),289.0,Grumpier Old Men (1995)Comedy|Romanceold,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285756,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fidark,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285757,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fiemotional,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285758,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Figritty,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285759,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fiheartbreaking,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285760,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fipredictible plot,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
pd.get_dummies(final_movies, columns=['genres', 'tag'], drop_first=True)

,movieId,rating,title,userId_y,overview,genres_Action|Adventure,genres_Action|Adventure|Animation|Children|Comedy,genres_Action|Adventure|Animation|Children|Comedy|Fantasy,genres_Action|Adventure|Animation|Children|Comedy|Sci-Fi,genres_Action|Adventure|Animation|Children|Fantasy|Sci-Fi,...,tag_women,tag_wonderwoman,tag_workplace,tag_writing,tag_wrongful imprisonment,tag_wry,tag_younger men,tag_zither,tag_zoe kazan,tag_zombies
0,1,4.0,Toy Story (1995),336.0,Toy Story (1995)Adventure|Animation|Children|C...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,4.0,Toy Story (1995),474.0,Toy Story (1995)Adventure|Animation|Children|C...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,4.0,Toy Story (1995),567.0,Toy Story (1995)Adventure|Animation|Children|C...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,4.0,Grumpier Old Men (1995),289.0,Grumpier Old Men (1995)Comedy|Romancemoldy,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3,4.0,Grumpier Old Men (1995),289.0,Grumpier Old Men (1995)Comedy|Romanceold,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285756,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fidark,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285757,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fiemotional,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285758,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Figritty,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285759,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fiheartbreaking,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
285760,168252,5.0,Logan (2017),567.0,Logan (2017)Action|Sci-Fipredictible plot,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [82]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [83]:
dfle = final_movies
le.fit_transform(dfle.genres)

array([115, 115, 115, ..., 105, 105, 105])

In [84]:
dfle.genres = le.fit_transform(dfle.genres)
dfle

,movieId,rating,title,genres,userId_y,tag
0,1,4.0,Toy Story (1995),115,336.0,pixar
1,1,4.0,Toy Story (1995),115,474.0,pixar
2,1,4.0,Toy Story (1995),115,567.0,fun
3,3,4.0,Grumpier Old Men (1995),259,289.0,moldy
4,3,4.0,Grumpier Old Men (1995),259,289.0,old
...,...,...,...,...,...,...
285756,168252,5.0,Logan (2017),105,567.0,dark
285757,168252,5.0,Logan (2017),105,567.0,emotional
285758,168252,5.0,Logan (2017),105,567.0,gritty
285759,168252,5.0,Logan (2017),105,567.0,heartbreaking
285760,168252,5.0,Logan (2017),105,567.0,predictible plot

In [ ]:
dfle = final_movies
le.fit_transform(dfle.genres)

In [62]:
X = final_movies[['title', 'overview', 'movieId']].values
X

array([['Toy Story (1995)',
        'Toy Story (1995)Adventure|Animation|Children|Comedy|Fantasypixar',
        1],
       ['Toy Story (1995)',
        'Toy Story (1995)Adventure|Animation|Children|Comedy|Fantasypixar',
        1],
       ['Toy Story (1995)',
        'Toy Story (1995)Adventure|Animation|Children|Comedy|Fantasyfun',
        1],
       ...,
       ['Logan (2017)', 'Logan (2017)Action|Sci-Figritty', 168252],
       ['Logan (2017)', 'Logan (2017)Action|Sci-Fiheartbreaking', 168252],
       ['Logan (2017)', 'Logan (2017)Action|Sci-Fipredictible plot',
        168252]], dtype=object)

In [48]:
new_df = final_movies[['movieId', 'title', 'overview']]
new_df

,movieId,title,overview
0,1,Toy Story (1995),Toy Story (1995)Adventure|Animation|Children|C...
1,1,Toy Story (1995),Toy Story (1995)Adventure|Animation|Children|C...
2,1,Toy Story (1995),Toy Story (1995)Adventure|Animation|Children|C...
3,3,Grumpier Old Men (1995),Grumpier Old Men (1995)Comedy|Romancemoldy
4,3,Grumpier Old Men (1995),Grumpier Old Men (1995)Comedy|Romanceold
...,...,...,...
285756,168252,Logan (2017),Logan (2017)Action|Sci-Fidark
285757,168252,Logan (2017),Logan (2017)Action|Sci-Fiemotional
285758,168252,Logan (2017),Logan (2017)Action|Sci-Figritty
285759,168252,Logan (2017),Logan (2017)Action|Sci-Fiheartbreaking
285760,168252,Logan (2017),Logan (2017)Action|Sci-Fipredictible plot

In [49]:
new_df['overview'][0]

'Toy Story (1995)Adventure|Animation|Children|Comedy|Fantasypixar'

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [24]:
cv.fit_transform(new_df['overview']).toarray().shape

(233213, 4974)

In [ ]:
vectors = cv.fit_transform(new_df['overview']).toarray()

In [26]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
len(cv.get_feature_names())

C:\Users\somep\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

4974

In [28]:
import nltk

In [29]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [30]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [31]:
new_df['overview'] = new_df['overview'].apply(stem)

C:\Users\somep\AppData\Local\Temp\ipykernel_8132\1662754065.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['overview'] = new_df['overview'].apply(stem)

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
cosine_similarity(X = new_df, Y=final_movies['genres_Action|Adventure'], dense_output=True)

KeyError: 'genres_Action|Adventure'

In [33]:
cosine_similarity(vectors)

MemoryError: Unable to allocate 8.64 GiB for an array with shape (233213, 4974) and data type float64

In [29]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import NearestNeighbors

In [30]:
# Obtain tf-idf scores using sklearn Tfidfvectorizor, setting max features at 250
tf = TfidfVectorizer(max_features=250)
dtm = tf.fit_transform(new_df['overview'])
# Transform the vectorizer output into a new dense dtm dataframe so it can merged with meta data
dtm = pd.DataFrame(dtm.todense(), columns=tf.get_feature_names_out(), index=new_df.index)
dtm.head()

,12,1960,1964,1968,1975,1977,1980,1981,1982,1983,...,twelve,unchained,up,usual,violence,war,wars,with,worrying,you
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
dtm.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 233213 entries, 0 to 285760
Columns: 250 entries, 12 to you
dtypes: float64(250)
memory usage: 454.7 MB

In [41]:
dtm.to_parquet('Data/df_dtm_new.parquet')

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

In [25]:
title = input('title: ')
movie = new_df.index[df_meta_all['title'] == title]
movie

KeyboardInterrupt: Interrupted by user

In [ ]:
y = np.array(new_df.loc[movie])
# Need to reshape so it can be passed into cosine_sim function
y = y.reshape(1, -1)
y

In [ ]:
cos_sim = cosine_similarity(new_df, y)
# Create a dataframe with similairty scores with book product ID ('asin') as index
cos_sim = pd.DataFrame(data=cos_sim, index=new_df.index)
cos_sim.head()

In [33]:
excel_file = pd.ExcelWriter("FINAL DATASET.xlsx")

In [34]:
masterfile.to_excel(excel_file)

In [35]:
excel_file.save()